title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-cayman


google_analytics:
background-image: http://sf6-tccdn-tos.pstatp.com/obj/tuchong-avatar/h_2301626_1

# You can use tuchong‘s page-content, css is fited.
include: gallery.html

images: 
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
      w: 1024
      h: 683
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
      w: 1024
      h: 683
    - title: 爱人
      src: 'https://photo.tuchong.com/2301626/ft640/209322359.jpg'
      w: 1024
      h: 683
